apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kuzoo-job.fullname" . }}
  labels:
    {{- include "kuzoo-job.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kuzoo-job.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.nameOverride }}
        image: "{{ .Values.image.repository }}/{{ .Values.nameOverride }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: {{ .Values.command }}
        {{- with .Values.env }}
        env:
          {{- toYaml . | nindent 10 }}
        {{- end }}

      restartPolicy: Never
  backoffLimit: 0
